import { GOOGLE_GERMAN_DECK_NAME } from "../lib/vocabulary-model.js";
import { selectWeightedCard } from "../lib/vocabulary-selection.js";
import { VocabularyStore } from "../lib/vocabulary-store.js";
import { GoogleSheetsSyncProvider, VocabularySyncService } from "../lib/vocabulary-sync.js";

export function initVocabularySyncUI({ showToast }) {
  const root = document.getElementById("vocabulary-sync-deck"); if (!root) return;
  const store = new VocabularyStore(); const provider = new GoogleSheetsSyncProvider(); const service = new VocabularySyncService(store, provider);
  let currentId = null; let recent = []; let syncTimer = null;
  const escapeHtml = (value) => String(value || "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
  const cardBox = root.querySelector("[data-vocab-card]"); const form = root.querySelector("[data-vocab-form]");
  const syncSoon = () => { clearTimeout(syncTimer); syncTimer = setTimeout(() => sync(false), 900); };
  function render() { const data = store.snapshot(); root.querySelector("[data-vocab-count]").textContent = `${data.cards.length} tarjetas`; root.querySelector("[data-vocab-pending]").textContent = data.queue.length ? `Cambios pendientes: ${data.queue.length}` : "Sincronizado"; root.querySelector("[data-vocab-last]").textContent = data.deck.lastSuccessfulSyncAt ? `Última sincronización: ${new Date(data.deck.lastSuccessfulSyncAt).toLocaleString()}` : (provider.configured ? "Aún no sincronizado" : "Sincronización pendiente de configurar"); }
  function showNext() { const card = selectWeightedCard(store.data.cards, recent); if (!card) { cardBox.innerHTML = '<p class="muted">Crea o sincroniza una tarjeta para empezar.</p>'; return; } currentId = card.id; recent.push(card.id); recent = recent.slice(-3); cardBox.innerHTML = `<p class="eyebrow">${escapeHtml(card.article)}</p><h3>${escapeHtml([card.article, card.word].filter(Boolean).join(" "))}</h3><button class="button ghost" type="button" data-reveal>Mostrar significado</button><div class="hidden" data-answer><p>${escapeHtml(card.meaning || "Sin significado")}</p><p>${escapeHtml(card.exampleSentence)}</p><p class="muted">${escapeHtml(card.exampleTranslation)}</p><button class="button ghost small" type="button" data-edit-example>${card.exampleSentence || card.exampleTranslation ? "Editar ejemplo" : "Añadir ejemplo"}</button><form class="hidden vocabulary-sync__form" data-example-form><label class="field"><span>Frase en alemán</span><textarea name="exampleSentence">${escapeHtml(card.exampleSentence)}</textarea></label><label class="field"><span>Traducción al español</span><textarea name="exampleTranslation">${escapeHtml(card.exampleTranslation)}</textarea></label><div class="row"><button class="button small" type="submit">Guardar ejemplo</button><button class="button ghost small" type="button" data-cancel-example>Cancelar</button></div></form><div class="review-actions">${[["unknown","No sabida"],["bad","Mala"],["good","Buena"],["easy","Fácil"]].map(([value,label])=>`<button class="button" type="button" data-vocab-rating="${value}">${label}</button>`).join("")}</div></div>`; }
  async function sync(notify = true) { root.dataset.syncing = "true"; render(); try { const result = await service.sync(); if (notify) showToast(result.pendingConfiguration ? "Guardado localmente. Configura Sheets para sincronizar." : "Sincronización completada.", result.pendingConfiguration ? "info" : "success"); } catch (error) { if (notify) showToast(error.message, "error"); } finally { delete root.dataset.syncing; render(); } }
  root.querySelector("[data-vocab-sync]").addEventListener("click", () => sync());
  root.querySelector("[data-vocab-new]").addEventListener("click", () => { form.reset(); form.classList.remove("hidden"); form.elements.word.focus(); });
  root.querySelector("[data-vocab-edit]").addEventListener("click", () => { const card=store.data.cards.find(item=>item.id===currentId); if(!card)return; form.reset(); for(const name of ["id","article","word","meaning","exampleSentence","exampleTranslation"]) form.elements[name].value=card[name]||""; form.elements.learned.checked=card.learned; form.classList.remove("hidden"); form.elements.word.focus(); });
  form.addEventListener("submit", (event) => { event.preventDefault(); const fields = Object.fromEntries(new FormData(form)); fields.learned=form.elements.learned.checked; try { if(fields.id) store.updateCard(fields.id,fields); else store.createCard(fields); form.classList.add("hidden"); render(); showNext(); showToast("Tarjeta guardada localmente."); syncSoon(); } catch (error) { if (!fields.id && error.message === "POSSIBLE_DUPLICATE" && confirm("Puede ser un duplicado. ¿Crear de todos modos?")) { store.createCard(fields, { allowDuplicate: true }); form.classList.add("hidden"); render(); showNext(); syncSoon(); } else if (error.message !== "POSSIBLE_DUPLICATE") showToast(error.message, "error"); } });
  form.querySelector("[data-vocab-cancel]").addEventListener("click", () => form.classList.add("hidden"));
  cardBox.addEventListener("click", (event) => { const reveal = event.target.closest("[data-reveal]"); if (reveal) { reveal.classList.add("hidden"); cardBox.querySelector("[data-answer]").classList.remove("hidden"); return; } const rating = event.target.closest("[data-vocab-rating]")?.dataset.vocabRating; if (rating && currentId) { event.target.disabled = true; store.rateCard(currentId, rating); render(); showNext(); syncSoon(); } if(event.target.closest("[data-edit-example]")){const editor=cardBox.querySelector("[data-example-form]");editor.classList.remove("hidden");editor.elements.exampleSentence.focus();} if(event.target.closest("[data-cancel-example]"))cardBox.querySelector("[data-example-form]").classList.add("hidden"); });
  cardBox.addEventListener("submit",event=>{if(!event.target.matches("[data-example-form]"))return;event.preventDefault();const fields=Object.fromEntries(new FormData(event.target));store.updateCard(currentId,fields);showNext();syncSoon();});
  window.addEventListener("online", () => sync(false)); render(); showNext(); sync(false);
}
