import { applyRating, createUuid, duplicateKey, GOOGLE_GERMAN_DECK_ID, mergeVocabularyCards, normalizeVocabularyCard, VOCABULARY_SCHEMA_VERSION } from "./vocabulary-model.js";
const KEY = "chanki_vocabulary_sync_v1";
const empty = () => ({ schemaVersion: VOCABULARY_SCHEMA_VERSION, deck: { id: GOOGLE_GERMAN_DECK_ID, lastSuccessfulSyncAt: null }, cards: [], queue: [], processedEventIds: [] });
export class VocabularyStore {
  constructor(storage = globalThis.localStorage) { this.storage = storage; this.data = this.load(); }
  load() { try { return this.migrate(JSON.parse(this.storage.getItem(KEY) || "null")); } catch (_) { return empty(); } }
  migrate(raw) { const data = raw && typeof raw === "object" ? raw : empty(); return { ...empty(), ...data, schemaVersion: VOCABULARY_SCHEMA_VERSION, cards: (data.cards || []).map((card) => normalizeVocabularyCard(card)), queue: [...new Map((data.queue || []).filter((change) => change?.eventId).map((change) => [change.eventId, change])).values()], processedEventIds: [...new Set(data.processedEventIds || [])] }; }
  persist() { this.storage.setItem(KEY, JSON.stringify(this.data)); return this.data; }
  snapshot() { return structuredClone(this.data); }
  enqueue(change) { if (!this.data.queue.some((item) => item.eventId === change.eventId)) this.data.queue.push(change); }
  createCard(fields, { allowDuplicate = false } = {}) { const card = normalizeVocabularyCard({ ...fields, id: createUuid(), createdAt: new Date().toISOString(), syncStatus: "pending_create" }); if (!card.word) throw new Error("La palabra es obligatoria"); if (!allowDuplicate && this.data.cards.some((item) => duplicateKey(item) === duplicateKey(card))) throw new Error("POSSIBLE_DUPLICATE"); this.data.cards.push(card); this.enqueue({ eventId: createUuid(), operation: "create", card }); this.persist(); return card; }
  updateCard(id, fields) { const index = this.data.cards.findIndex((card) => card.id === id); if (index < 0) throw new Error("Tarjeta no encontrada"); const status = this.data.cards[index].syncStatus === "pending_create" ? "pending_create" : "pending_update"; const card = normalizeVocabularyCard({ ...this.data.cards[index], ...fields, id, updatedAt: new Date().toISOString(), syncStatus: status }); this.data.cards[index] = card; this.enqueue({ eventId: createUuid(), operation: "update", card }); this.persist(); return card; }
  rateCard(id, rating, eventId = createUuid()) { if (this.data.processedEventIds.includes(eventId)) return this.data.cards.find((card) => card.id === id); const index = this.data.cards.findIndex((card) => card.id === id); if (index < 0) throw new Error("Tarjeta no encontrada"); const card = applyRating(this.data.cards[index], rating); this.data.cards[index] = card; this.data.processedEventIds.push(eventId); this.enqueue({ eventId, operation: "rate", cardId: id, rating, updatedAt: card.updatedAt }); this.persist(); return card; }
  mergeRemote(cards) { for (const remote of cards) { const index = this.data.cards.findIndex((card) => card.id === remote.id); if (index < 0) this.data.cards.push(normalizeVocabularyCard({ ...remote, source: "google_sheets", syncStatus: "synced" })); else this.data.cards[index] = mergeVocabularyCards(this.data.cards[index], remote); } this.persist(); }
  acknowledge(results) { const ok = new Set(results.filter((result) => result.success).map((result) => result.eventId)); this.data.queue = this.data.queue.filter((change) => !ok.has(change.eventId)); for (const result of results) { if (!result.success) continue; const card = this.data.cards.find((item) => item.id === result.cardId); if (card) { if (Number.isInteger(result.position)) card.position = result.position; card.syncStatus = "synced"; card.remoteUpdatedAt = result.updatedAt; } } this.persist(); }
}
