/** Chanki ↔ Google Sheets. Configure las Script Properties antes de desplegar. */
const DEFAULT_SHEET_NAME = 'Charly';
const REQUIRED_HEADERS = ['Puesto','der die das','Palabra','Significado','Frase','Significado frase','Sabida?','Veces no sabida','Veces mala','Veces buena','Veces fácil','ID','Actualizado'];
const HEADER_ALIASES = {
  position:['puesto'], article:['der die das','articulo'], word:['palabra'], meaning:['significado'],
  exampleSentence:['frase'], exampleTranslation:['significado frase','traduccion frase'], learned:['sabida','sabida?'],
  unknownCount:['veces no sabida'], badCount:['veces mala'], goodCount:['veces buena'], easyCount:['veces facil'], id:['id'], updatedAt:['actualizado']
};
function normalizeHeader_(value) { return String(value || '').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, ' '); }
function config_() { const p=PropertiesService.getScriptProperties(); return { spreadsheetId:p.getProperty('SPREADSHEET_ID'), sheetName:p.getProperty('SHEET_NAME')||DEFAULT_SHEET_NAME, token:p.getProperty('CHANKI_SYNC_TOKEN') }; }
function sheet_() { const c=config_(); if(!c.spreadsheetId) throw new Error('Configuración incompleta'); const s=SpreadsheetApp.openById(c.spreadsheetId).getSheetByName(c.sheetName); if(!s) throw new Error('Pestaña no encontrada'); return s; }
function json_(body) { return ContentService.createTextOutput(JSON.stringify(body)).setMimeType(ContentService.MimeType.JSON); }
function authorized_(body) { const expected=config_().token; return Boolean(expected && body && typeof body.token==='string' && body.token===expected); }
function parse_(event) { try { return JSON.parse(event.postData.contents); } catch (_) { throw new Error('JSON no válido'); } }
function columns_(sheet) { const values=sheet.getRange(1,1,1,Math.max(sheet.getLastColumn(),1)).getValues()[0]; const normalized=values.map(normalizeHeader_); const out={}; Object.keys(HEADER_ALIASES).forEach(k=>{ const aliases=HEADER_ALIASES[k].map(normalizeHeader_); const i=normalized.findIndex(h=>aliases.indexOf(h)>=0); if(i>=0) out[k]=i; }); return out; }
function num_(value) { const n=Math.trunc(Number(value)||0); return Math.max(0,n); }
function bool_(value) { return value===true || ['true','verdadero','si','sí','1'].indexOf(normalizeHeader_(value))>=0; }
function iso_(value) { if(value instanceof Date) return value.toISOString(); const parsed=new Date(value); return isNaN(parsed.getTime())?'':parsed.toISOString(); }
function isEmptyRow_(row,c) { return !String(row[c.word]||'').trim() && !String(row[c.id]||'').trim() && !String(row[c.meaning]||'').trim() && !String(row[c.exampleSentence]||'').trim(); }
function card_(row,c) { return { id:String(row[c.id]||''), position:Number(row[c.position])||null, article:['der','die','das'].indexOf(normalizeHeader_(row[c.article]))>=0?normalizeHeader_(row[c.article]):null, word:String(row[c.word]||'').trim(), meaning:String(row[c.meaning]||'').trim(), exampleSentence:String(row[c.exampleSentence]||'').trim(), exampleTranslation:String(row[c.exampleTranslation]||'').trim(), learned:bool_(row[c.learned]), unknownCount:num_(row[c.unknownCount]), badCount:num_(row[c.badCount]), goodCount:num_(row[c.goodCount]), easyCount:num_(row[c.easyCount]), updatedAt:iso_(row[c.updatedAt])||new Date(0).toISOString(), source:'google_sheets', syncStatus:'synced' }; }
function allCards_(sheet,c,writeIds) { const last=sheet.getLastRow(); if(last<3)return[]; const range=sheet.getRange(3,1,last-2,sheet.getLastColumn()), rows=range.getValues(), cards=[]; rows.forEach((row,i)=>{ if(isEmptyRow_(row,c))return; if(!row[c.id]&&writeIds){row[c.id]=Utilities.getUuid(); row[c.updatedAt]=new Date(); range.getCell(i+1,c.id+1).setValue(row[c.id]); range.getCell(i+1,c.updatedAt+1).setValue(row[c.updatedAt]);} cards.push(card_(row,c)); }); return cards; }
function nextPosition_(cards) { return cards.reduce((max,card)=>Math.max(max,Number(card.position)||0),0)+1; }
function set_(row,c,key,value) { if(c[key]!==undefined) row[c[key]]=value; }
function writeCard_(sheet,c,rowNumber,card,position) { const width=sheet.getLastColumn(); const row=rowNumber?sheet.getRange(rowNumber,1,1,width).getValues()[0]:Array(width).fill(''); const now=new Date(); set_(row,c,'position',position||card.position||''); set_(row,c,'article',card.article||''); set_(row,c,'word',String(card.word||'').trim()); set_(row,c,'meaning',card.meaning||''); set_(row,c,'exampleSentence',card.exampleSentence||''); set_(row,c,'exampleTranslation',card.exampleTranslation||''); set_(row,c,'learned',Boolean(card.learned)||num_(card.easyCount)>=10); ['unknownCount','badCount','goodCount','easyCount'].forEach(k=>set_(row,c,k,num_(card[k]))); set_(row,c,'id',card.id); set_(row,c,'updatedAt',now); const target=rowNumber||sheet.getLastRow()+1; sheet.getRange(target,1,1,width).setValues([row]); return {row:target,updatedAt:now.toISOString()}; }
function eventKey_(eventId) { return 'event_'+Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,eventId)).slice(0,32); }
function applyChange_(sheet,c,change,cards) { if(!change||!change.eventId) throw new Error('eventId obligatorio'); const props=PropertiesService.getScriptProperties(), key=eventKey_(change.eventId), cached=props.getProperty(key); if(cached)return JSON.parse(cached); const id=String(change.cardId||change.card&&change.card.id||''), index=cards.findIndex(x=>x.id===id), row=index>=0?index+3:null; let card=change.card||cards[index]; if(!card) throw new Error('Tarjeta no encontrada'); if(change.operation==='rate'){ card=Object.assign({},card); const field={unknown:'unknownCount',bad:'badCount',good:'goodCount',easy:'easyCount'}[change.rating]; if(!field)throw new Error('Valoración inválida'); card[field]=num_(card[field])+1; if(card.easyCount>=10)card.learned=true; } else if(['create','update'].indexOf(change.operation)<0) throw new Error('Operación no permitida'); if(change.operation==='create'&&row) throw new Error('El ID ya existe'); const assignedPosition=change.operation==='create'?nextPosition_(cards):card.position; const written=writeCard_(sheet,c,row,card,assignedPosition); card.position=assignedPosition; card.updatedAt=written.updatedAt; if(index>=0)cards[index]=card; else cards.push(card); const result={eventId:change.eventId,success:true,cardId:id,position:Number(assignedPosition)||null,updatedAt:written.updatedAt}; props.setProperty(key,JSON.stringify(result)); return result; }
function doGet() { try { return json_({ok:true,serverTime:new Date().toISOString(),sheetName:config_().sheetName}); } catch(_){return json_({ok:false,error:'No disponible'});} }
function doPost(event) { try { const body=parse_(event); if(!authorized_(body))return json_({ok:false,error:'No autorizado'}); const action=body.action; if(action==='ping')return json_({ok:true,serverTime:new Date().toISOString(),sheetName:config_().sheetName}); const sheet=sheet_(), c=columns_(sheet); if(action==='pull'){const since=body.since?new Date(body.since).getTime():0; const cards=allCards_(sheet,c,true).filter(x=>new Date(x.updatedAt).getTime()>since); return json_({ok:true,serverTime:new Date().toISOString(),cards:cards});} if(action==='push'){const lock=LockService.getScriptLock(); lock.waitLock(20000); try {const cards=allCards_(sheet,c,true), results=(body.changes||[]).map(change=>{try{return applyChange_(sheet,c,change,cards);}catch(_){return {eventId:change&&change.eventId||'',success:false,error:'No se pudo aplicar el cambio'};}}); return json_({ok:true,serverTime:new Date().toISOString(),results:results});}finally{lock.releaseLock();}} throw new Error('Acción no válida'); } catch(_){return json_({ok:false,error:'Solicitud no procesada'});} }
/** Ejecutar manualmente una vez: añade sin borrar las columnas necesarias. */
function setupChankiSheet() { const sheet=sheet_(); const existing=sheet.getRange(1,1,1,Math.max(sheet.getLastColumn(),1)).getValues()[0].map(normalizeHeader_); REQUIRED_HEADERS.forEach(h=>{if(existing.indexOf(normalizeHeader_(h))<0)sheet.getRange(1,sheet.getLastColumn()+1).setValue(h);}); }
/** Ejecutar tras setupChankiSheet para completar UUID y Actualizado en filas antiguas. */
function backfillChankiIds() { const sheet=sheet_(); allCards_(sheet,columns_(sheet),true); }
